In [14]:
# Imports and file path
import duckdb
from pathlib import Path

acs5_parquet_path = Path("../data/normalized/acs5_2024.parquet")
tiger_parquet_path = Path("../data/normalized/tiger_geospatial_tracts.parquet")
lcdv2_parquet_path = Path("../data/normalized/lcdv2/station_id=WBAN_00183/year=2025/part.parquet")
station_elevation = Path("../data/raw/elevation/station_elevation.parquet")
tract_elevation = Path("../data/raw/elevation/tract_elevation.parquet")

In [2]:
# Preview first 10 rows
duckdb.query(f"""
    SELECT *
    FROM '{acs5_parquet_path.as_posix()}'
    LIMIT 10
""").df()

,state,county,tract_code,tract,population_total,population_male,population_female,male_65_66,male_67_69,male_70_74,...,vehicle_none,housing_structure_universe,housing_1_unit,housing_2_unit,housing_3_4_unit,housing_5_9_unit,housing_10_19_unit,housing_20_49_unit,housing_50_plus_unit,housing_mobile_home
0,55,001,950100,55001950100,3415,1695,1720,123,211,192,...,18,3312,58,0,17,57,0,0,0,309
1,55,001,950201,55001950201,1564,813,751,36,49,133,...,30,1571,12,14,0,213,0,11,1,225
2,55,001,950203,55001950203,1089,659,430,51,53,65,...,27,956,8,5,0,0,0,0,0,302
3,55,001,950204,55001950204,2060,1183,877,61,54,142,...,23,1897,19,0,0,68,7,0,0,336
4,55,001,950400,55001950400,4753,2434,2319,121,89,130,...,138,2633,43,40,88,109,44,11,42,339
5,55,001,950501,55001950501,1534,828,706,45,51,97,...,82,2032,10,0,0,0,0,0,0,572
6,55,001,950502,55001950502,3128,1934,1194,25,87,137,...,35,2048,25,28,29,38,97,8,0,544
7,55,001,950700,55001950700,3580,1947,1633,69,105,115,...,48,2559,47,19,29,0,0,0,36,452
8,55,003,940000,55003940000,1887,975,912,19,24,41,...,63,882,10,4,8,10,6,0,2,193
9,55,003,950300,55003950300,2680,1528,1152,36,19,56,...,44,1248,30,151,45,16,66,35,0,19

In [3]:
# Record Count
duckdb.query(f"""
    SELECT COUNT(*) AS station_count
    FROM '{acs5_parquet_path.as_posix()}'
""").df()

   station_count
0           1542

In [4]:
# Preview first 10 rows
duckdb.query(f"""
    SELECT *
    FROM '{tiger_parquet_path.as_posix()}'
    LIMIT 10
""").df()

,tract,state_fips,county_fips,tract_code,name,aland,awater,centroid_lat,centroid_lon,bbox_minx,bbox_miny,bbox_maxx,bbox_maxy,geometry_wkb
0,55001950204,55,001,950204,9502.04,353539615,49159328,44.072876,-89.799925,-90.026378,43.981852,-89.597929,44.178603,"[1, 3, 0, 0, 0, 1, 0, 0, 0, 140, 4, 0, 0, 94, ..."
1,55001950203,55,001,950203,9502.03,114351980,1368834,44.119251,-89.729368,-89.858155,44.052500,-89.597699,44.164470,"[1, 3, 0, 0, 0, 1, 0, 0, 0, 216, 0, 0, 0, 135,..."
2,55009940002,55,009,940002,9400.02,11531694,0,44.515753,-88.125973,-88.150185,44.495776,-88.104134,44.543117,"[1, 3, 0, 0, 0, 1, 0, 0, 0, 90, 1, 0, 0, 98, 2..."
3,55009001600,55,009,001600,16,3538241,8847,44.488816,-87.982837,-87.994821,44.473492,-87.969300,44.505105,"[1, 3, 0, 0, 0, 1, 0, 0, 0, 190, 0, 0, 0, 247,..."
4,55009001801,55,009,001801,18.01,11713129,34950,44.514316,-87.915659,-87.955545,44.495293,-87.879198,44.529021,"[1, 3, 0, 0, 0, 1, 0, 0, 0, 146, 0, 0, 0, 120,..."
5,55009001802,55,009,001802,18.02,20140123,20678230,44.543620,-87.938263,-88.007769,44.519053,-87.875322,44.574676,"[1, 3, 0, 0, 0, 1, 0, 0, 0, 214, 0, 0, 0, 44, ..."
6,55009002001,55,009,002001,20.01,6976236,13298,44.497915,-87.959372,-87.985653,44.487255,-87.936758,44.508792,"[1, 3, 0, 0, 0, 1, 0, 0, 0, 131, 0, 0, 0, 123,..."
7,55009002002,55,009,002002,20.02,3632749,0,44.480447,-87.956468,-87.974142,44.471225,-87.940303,44.490308,"[1, 3, 0, 0, 0, 1, 0, 0, 0, 125, 0, 0, 0, 242,..."
8,55009002003,55,009,002003,20.03,13565397,16425,44.487670,-87.913746,-87.945308,44.472937,-87.887175,44.507500,"[1, 3, 0, 0, 0, 1, 0, 0, 0, 79, 0, 0, 0, 194, ..."
9,55009010100,55,009,010100,101,4789500,496893,44.449755,-88.043006,-88.068296,44.437495,-88.013619,44.464872,"[1, 3, 0, 0, 0, 1, 0, 0, 0, 237, 0, 0, 0, 101,..."

In [5]:
# Record Count
duckdb.query(f"""
    SELECT COUNT(*) AS station_count
    FROM '{tiger_parquet_path.as_posix()}'
""").df()

   station_count
0           1542

In [6]:
# Preview first 10 rows
duckdb.query(f"""
    SELECT *
    FROM '{lcdv2_parquet_path.as_posix()}'
    LIMIT 10
""").df()

,station,timestamp,dry_bulb_temp,wet_bulb_temp,dew_point_temp,relative_humidity,wind_speed,wind_direction,wind_gust_speed,precipitation,visibility,station_pressure,barometric_pressure,station_id,year
0,WBAN:00183,2025-01-01 00:15:00,29.0,27.0,24.0,80.0,16.0,280.0,23.0,NaN,10.0,28.92,30.01,WBAN_00183,2025
1,WBAN:00183,2025-01-01 00:35:00,29.0,27.0,23.0,78.0,16.0,300.0,22.0,NaN,10.0,28.92,30.01,WBAN_00183,2025
2,WBAN:00183,2025-01-01 00:55:00,29.0,27.0,24.0,80.0,10.0,280.0,21.0,NaN,10.0,28.92,30.01,WBAN_00183,2025
3,WBAN:00183,2025-01-01 01:15:00,29.0,27.0,22.0,77.0,16.0,280.0,23.0,NaN,10.0,28.92,30.01,WBAN_00183,2025
4,WBAN:00183,2025-01-01 01:35:00,28.0,26.0,21.0,75.0,14.0,280.0,18.0,NaN,10.0,28.92,30.02,WBAN_00183,2025
5,WBAN:00183,2025-01-01 01:55:00,27.0,25.0,20.0,74.0,16.0,270.0,21.0,NaN,10.0,28.92,30.02,WBAN_00183,2025
6,WBAN:00183,2025-01-01 02:15:00,26.0,24.0,20.0,77.0,13.0,280.0,NaN,NaN,10.0,28.92,30.02,WBAN_00183,2025
7,WBAN:00183,2025-01-01 02:35:00,26.0,24.0,20.0,76.0,15.0,280.0,18.0,NaN,10.0,28.94,30.03,WBAN_00183,2025
8,WBAN:00183,2025-01-01 02:55:00,26.0,24.0,20.0,75.0,14.0,280.0,NaN,NaN,10.0,28.94,30.03,WBAN_00183,2025
9,WBAN:00183,2025-01-01 03:15:00,27.0,25.0,21.0,79.0,13.0,280.0,20.0,NaN,10.0,28.94,30.03,WBAN_00183,2025

In [7]:
# Record Count
duckdb.query(f"""
    SELECT COUNT(*) AS station_count
    FROM '{lcdv2_parquet_path.as_posix()}'
""").df()

   station_count
0          16940

In [ ]:
# Most recently available dates from most recently available year
duckdb.query(f"""
    SELECT station, timestamp
    FROM '{lcdv2_parquet_path.as_posix()}'
    ORDER BY timestamp DESC
    LIMIT 50
""").df()

       station           timestamp
0   WBAN:00183 2025-08-25 05:55:00
1   WBAN:00183 2025-08-25 05:35:00
2   WBAN:00183 2025-08-25 05:15:00
3   WBAN:00183 2025-08-25 04:55:00
4   WBAN:00183 2025-08-25 04:35:00
5   WBAN:00183 2025-08-25 04:15:00
6   WBAN:00183 2025-08-25 03:55:00
7   WBAN:00183 2025-08-25 03:35:00
8   WBAN:00183 2025-08-25 03:15:00
9   WBAN:00183 2025-08-25 02:55:00
10  WBAN:00183 2025-08-25 02:35:00
11  WBAN:00183 2025-08-25 02:15:00
12  WBAN:00183 2025-08-25 01:55:00
13  WBAN:00183 2025-08-25 01:35:00
14  WBAN:00183 2025-08-25 01:15:00
15  WBAN:00183 2025-08-25 00:55:00
16  WBAN:00183 2025-08-25 00:35:00
17  WBAN:00183 2025-08-25 00:15:00
18  WBAN:00183 2025-08-24 23:55:00
19  WBAN:00183 2025-08-24 23:35:00
20  WBAN:00183 2025-08-24 23:15:00
21  WBAN:00183 2025-08-24 22:55:00
22  WBAN:00183 2025-08-24 22:35:00
23  WBAN:00183 2025-08-24 22:15:00
24  WBAN:00183 2025-08-24 21:55:00
25  WBAN:00183 2025-08-24 21:35:00
26  WBAN:00183 2025-08-24 21:15:00
27  WBAN:00183 2025-08-24 20:55:00
28  WBAN:00183 2025-08-24 20:35:00
29  WBAN:00183 2025-08-24 20:15:00
30  WBAN:00183 2025-08-24 19:55:00
31  WBAN:00183 2025-08-24 19:35:00
32  WBAN:00183 2025-08-24 19:15:00
33  WBAN:00183 2025-08-24 18:55:00
34  WBAN:00183 2025-08-24 18:35:00
35  WBAN:00183 2025-08-24 18:15:00
36  WBAN:00183 2025-08-24 17:55:00
37  WBAN:00183 2025-08-24 17:35:00
38  WBAN:00183 2025-08-24 17:15:00
39  WBAN:00183 2025-08-24 16:55:00
40  WBAN:00183 2025-08-24 16:35:00
41  WBAN:00183 2025-08-24 16:15:00
42  WBAN:00183 2025-08-24 15:55:00
43  WBAN:00183 2025-08-24 15:35:00
44  WBAN:00183 2025-08-24 15:15:00
45  WBAN:00183 2025-08-24 14:55:00
46  WBAN:00183 2025-08-24 14:35:00
47  WBAN:00183 2025-08-24 14:15:00
48  WBAN:00183 2025-08-24 13:55:00
49  WBAN:00183 2025-08-24 13:35:00

In [11]:
# Preview first 10 rows
duckdb.query(f"""
    SELECT *
    FROM '{station_elevation.as_posix()}'
    LIMIT 10
""").df()

      station  latitude  longitude  elevation_m
0  WBAN:00132  44.03300  -89.30000   260.397308
1  WBAN:00183  42.68300  -90.45000   294.559204
2  WBAN:00185  44.78300  -88.55000   247.757690
3  WBAN:00236  43.11700  -89.53300   282.868744
4  WBAN:00241  43.57900  -90.91300   371.609070
5  WBAN:00286  44.25100  -90.85500   252.356125
6  WBAN:00297  46.11700  -89.88300   489.386108
7  WBAN:00316  45.50600  -91.98100   377.412567
8  WBAN:00464  44.87405  -87.90977   183.215668
9  WBAN:04803  45.63143  -89.48240   493.180817

In [15]:
# Preview first 10 rows
duckdb.query(f"""
    SELECT *
    FROM '{tract_elevation.as_posix()}'
    LIMIT 10
""").df()

         tract  centroid_lat  centroid_lon  elevation_m
0  55009002002     44.480447    -87.956468   206.170639
1  55009001600     44.488816    -87.982837   182.571045
2  55001950204     44.072876    -89.799925   300.421112
3  55001950203     44.119251    -89.729368   309.204346
4  55009001801     44.514316    -87.915659   235.376755
5  55009002003     44.487670    -87.913746   237.788651
6  55117011302     43.585491    -87.870898   229.108612
7  55117010504     43.756903    -88.008430   272.392426
8  55117011301     43.595744    -87.791459   213.278320
9  55117010503     43.734073    -87.973158   250.045120